"""Nouvelle table ordi associé à un utilisateur

Revision ID: 1c014b960d8f
Revises: b25d2d7fbe11
Create Date: 2024-07-09 16:10:56.870054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c014b960d8f'
down_revision: Union[str, None] = 'b25d2d7fbe11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'computers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'computers', type_='foreignkey')
    op.drop_column('computers', 'user_id')
    # ### end Alembic commands ###
